let User,CustomeErrorHandler;_b29‍.x([["default",()=>_b29‍.o]]);_b29‍.w("../../models",[["User",["User"],function(v){User=v}]]);_b29‍.w("../../services/CustomeErrorHandling",[["default",["CustomeErrorHandler"],function(v){CustomeErrorHandler=v}]]);


const userController = {
  async me(req,res,next){
    try{
        const user = await User.findOne({_id:req.user._id}).select('-password -updatedAt -__v')  // this user is come from auth middelware
        if(!user) {
            return next(CustomeErrorHandler.notFound());
        }
        res.json(user);

    }catch(error){
      return  next(error)
    }
   }

}

_b29‍.d(userController);